<script src="//cdn.tinymce.com/4/tinymce.min.js"></script>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.9.0/themes/base/jquery-ui.css" />
<script src="http://code.jquery.com/jquery-1.8.2.js"></script>
<script src="http://code.jquery.com/ui/1.9.0/jquery-ui.js"></script>
<script src="http://files.rafaelwendel.com/jquery.maskedinput.js"></script>
<script src="https://raw.githubusercontent.com/plentz/jquery-maskmoney/master/dist/jquery.maskMoney.min.js"></script>

<script>

$("#salario").change(function(){
           $("#salario").maskMoney({decimal:",", thousands:"."});
});

$(function() {
    $( "#data_de_nascimento" ).datepicker();
    $( "#data_admissao" ).datepicker();
		$(document).ready(function(){
				tinymce.init({
						 plugins:"paste",
						 menubar: "false",
						 toolbar: "false",
				     statusbar: false,
						 paste_as_text: true,
						 selector: 'textarea',
						 height: 50,
						 width: 300,
						 setup: function (ed) {
					       ed.on('init', function (e) {
					//	 ExecucaoDaFuncaoLimiterPag('id');
									}).on('keyup',function (e) {
					// ExecucaoDaFuncaoLimiterPag('id');
					       });
						 }
				});



        $("#telefone").change(function() {
            $("#telefone").mask("(99)99999-9999");
        });

        $("#cpf").change(function() {
            $("#cpf").mask("999.999.999-99");
        });

        $("#rg").change(function() {
            $("#rg").mask("9.999.999");
        });



				//  $("#btn_salvar").click(function(e) {
        //    validacaonome = false;
        //    validacaorg = false;
        //    validacaocpf = false;
        //    validacaodata_de_nascimento = false;
        //    validacaonacionalidade = false;
        //    validacaocor = false;
        //    validacaoescolaridade = false;
        //    validacaouf = false;
        //    validacaocidade = false;
        // //   validacaocomplemento = false,
        //    validacaotelefone = false;
        //    validacaoemail = false;
        //    validacaosalario = false;
        //    validacaodata_admissao = false;
        //
        //
        //    if(document.getElementById("nome").value.length > 0){
        //        validacaonome = true;
        //
        //    }else{
        //         $("#msgnome").html("<font color='red'>Preencha o campo Nome!</font>");
        //
        //    }
        //    if(document.getElementById("rg").value.length > 0){
        //        validacaorg = true;
        //
        //    }else{
        //         $("#msgrg").html("<font color='red'>Preencha o campo RG!</font>");
        //
        //    }
        //    if(document.getElementById("cpf").value.length > 0){
        //        validacaocpf = true;
        //
        //    }else{
        //         $("#msgcpf").html("<font color='red'>Preencha o campo CPF!</font>");
        //
        //    }
        //    if(document.getElementById("data_de_nascimento").value.length > 0){
        //        validacaodata_de_nascimento = true;
        //
        //    }else{
        //         $("#msgdata_de_nascimento").html("<font color='red'>Preencha o campo Data de Nascimento!</font>");
        //
        //    }
        //    if(document.getElementById("nacionalidade").value.length > 0){
        //        validacanacionalidade = true;
        //
        //    }else{
        //         $("#msgpais_de_nascimento").html("<font color='red'>Preencha o campo Nacionalidade!</font>");
        //
        //     }
        //    if(document.getElementById("cor").value.length > 0){
        //        validacaocor = true;
        //
        //    }else{
        //         $("#msgcor").html("<font color='red'>Preencha o campo Cor/Etnia!</font>");
        //
        //    }
        //    if(document.getElementById("escolaridade").value.length > 0){
        //        validacaoescolaridade = true;
        //
        //    }else{
        //         $("#msgescolaridade").html("<font color='red'>Preencha o campo Escolaridade!</font>");
        //
        //    }
        //    if(document.getElementById("uf").value.length > 0){
        //        validacaouf = true;
        //
        //    }else{
        //         $("#msguf").html("<font color='red'>Preencha o campo Estado!</font>");
        //
        //    }
        //    if(document.getElementById("cidade").value.length > 0){
        //        validacaocidade = true;
        //
        //    }else{
        //         $("#msgcidade").html("<font color='red'>Preencha o campo Cidade!</font>");
        //
        //    }
        //
        //    if(document.getElementById("telefone").value.length > 0){
        //        validacaotelefone = true;
        //
        //    }else{
        //         $("#msgtelefone").html("<font color='red'>Preencha o campo Celular!</font>");
        //
        //    }
        //    if(document.getElementById("email").value.length > 0){
        //
        //
        //    }else{
        //         $("#msgemail").html("<font color='red'>Preencha o campo Email!</font>");
        //
        //    }
        //    if(document.getElementById("salario").value.length > 0){
        //        validacaosalario = true;
        //
        //    }else{
        //         $("#msgsalario").html("<font color='red'>Preencha o campo Salario!</font>");
        //
        //    }
        //    if(document.getElementById("data_admissao").value.length > 0){
        //        validacaodata_admissao = true;
        //
        //    }else{
        //         $("#msgdata_admissao").html("<font color='red'>Preencha o campo Data de Admissão!</font>");
        //
        //    }
        //
        //
        //    if(
        //      validacaonome == true &&
        //       validacaorg == true &&
        //       validacaocpf == true &&
        //       validacaodata_de_nascimento == true &&
        //       validacaonacionalidade == true &&
        //       validacaocor == true &&
        //       validacaoescolaridade == true &&
        //       validacaouf == true &&
        //       validacaocidade == true &&
        //       validacaocomplemento == true &&
        //       validacaotelefone == true &&
        //       validacaoemail == true &&
        //       validacaosalario == true &&
        //       validacaodata_admissao == true
        //    ){
        //     $("#cadastro").submit();
        //    }else{
        //
        //     return false;
        //    }
        //
        //
				//  });
		});
});
</script>

<form id="cadastro" name="form" method="POST" action="/application/funcionario/create">
   <fieldset>
     <legend>Dados Pessoais</legend>
    	<label>Nome</label>
    	<input type="text" name="nome" id="nome"/>
    	<div id="msgnome"></div>
    	<br/>

    	<label>RG</label>
    	<input type="text" name="rg" id="rg"/>
    	<div id="msgrg"></div>
    	<br/>

    	<label>CPF</label>
    	<input type="text" name="cpf" id="cpf"/>
    	<div id="msgcpf"></div>
    	<br/>

    	<label>Data de Nascimento</label>
    	<input type="date" name="data_de_nascimento" size="9" id="data_de_nascimento"/>
    	<div id="msgdata_de_nascimento"></div>
    	<br/>

    	<label>Nacionalidade</label>
    	<input type="text" name="pais_de_nascimento" id="nacionalidade"/>
    	<div id="msgnacionalidade"></div>
    	<br/>

    	<label>Cor/Etinia</label>
    	<input type="text" name="cor" id="cor" />
    	<div id="msgcor"></div>
    	<br/>

    	<label>Escolaridade</label>
    	<input type="text" name="escolaridade" id="escolaridade"/>
    	<div id="msgescolaridade"></div>
    	<br/>

      <label>Estado</label>
    <select name="uf" id="uf">
    		<option value="">Selecione</option>
    		<option value="AC">Acre</option>
    		<option value="AL">Alagoas</option>
    		<option value="AP">Amapá</option>
    		<option value="AM">Amazonas</option>
    		<option value="BA">Bahia</option>
    		<option value="CE">Ceará</option>
    		<option value="DF">Distrito Federal</option>
    		<option value="ES">Espirito Santo</option>
    		<option value="GO">Goiás</option>
    		<option value="MA">Maranhão</option>
    		<option value="MS">Mato Grosso do Sul</option>
    		<option value="MT">Mato Grosso</option>
    		<option value="MG">Minas Gerais</option>
    		<option value="PA">Pará</option>
    		<option value="PB">Paraíba</option>
    		<option value="PR">Paraná</option>
    		<option value="PE">Pernambuco</option>
    		<option value="PI">Piauí</option>
    		<option value="RJ">Rio de Janeiro</option>
    		<option value="RN">Rio Grande do Norte</option>
    		<option value="RS">Rio Grande do Sul</option>
    		<option value="RO">Rondônia</option>
    		<option value="RR">Roraima</option>
    		<option value="SC">Santa Catarina</option>
    		<option value="SP">São Paulo</option>
    		<option value="SE">Sergipe</option>
    		<option value="TO">Tocantins</option>
    </select>
    	<div id="msguf"></div>
    	<br/>

    	<label>Cidade</label>
    	<input type="text" name="cidade" id="cidade"/>
    	<div id="msgcidade"></div>
    	<br/>

    	<label>Complemento</label>
    	<textarea type="text" name="complemento" placeholder="Digite todos os dados e referências do endereço" row="30"></textarea>
      <div id="msgcomplemento"></div>
    	<br/>
    	<br/>

   </fieldset>
   <fielset>
       <legend>Dados Empresariais</legend>
        <label>Telefone Celular</label>
       	<input type="text" name="telefone" id="telefone"/>
        <div id="msgtelefone"></div>
       	<br/>
       	<br/>

        <label>Email</label>
        <input type="text" name="email" />
        <div id="msgemail"></div>
        <br/>
        <br/>

        <label>Salario</label>
      	<input id="salario" type="text" name="salario" />
        <div id="msgsalario"></div>
      	<br/>
      	<br/>

        <label>Data de Admissão</label>
      	<input type="date" name="data_admissao" size="9" id="data_admissao"/>
      	<div id="msgdata_admissao"></div>

   </fieldset>
   </br>
   </br>
   <center><button class="btn btn-success" id="btn_salvar" type="submit">Enviar</button></center>
</form>
