<form name="form" method="POST" action="/application/funcionario/create">
	<label>Nome</label>
	<input type="text" name="nome" />
	<br/>
	<label>Data de Nascimento</label>
	<input type="text" name="data_de_nascimento" />
	<br/>
	<label>Nacionalidade</label>
	<input type="text" name="pais_de_nascimento" />
	<br/>
	<label>Cor/Etinia</label>
	<input type="text" name="cor" />
	<br/>
	<label>Escolaridade</label>
	<input type="text" name="escolaridade" />
	<br/>
	<label>UF</label>
	<input type="text" name="uf" />
	<br/>
	<label>Cidade</label>
	<input type="text" name="cidade" />
	<br/>
	<label>Complemento</label>
	<input type="text" name="complemento" />
	<br/>
	<label>Data de Admissão</label>
	<input type="text" name="data_admissao" />
	<br/>
	<label>Salario</label>
	<input type="text" name="salario" />
	<br/>
	<label>Telefone</label>
	<input type="text" name="telefone" />
	<br/>
	<label>Email</label>
	<input type="text" name="email" />
	<br/>
	<button class="btn btn-success" type="submit">Enviar</button>
</form>
